/**
 * Bancos de tarefas: rituais (Crescimento) e sugestões (Meu dia).
 */
(function (g) {
  g.MM_RITUAL_POOL = [
    { id: 'tummy', title: 'Hora da barriguinha (15 min)', subtitle: 'Fortalecimento de pescoço e tronco', points: 15 },
    { id: 'story', title: 'História de ninar ou conto curto', subtitle: 'Linguagem e vínculo', points: 25 },
    { id: 'steps', title: 'Treino de apoio para ficar em pé', subtitle: 'Supervisionado, sem forçar', points: 50 },
    { id: 'outdoor', title: 'Ar puro ao ar livre', subtitle: 'Luz natural e sons novos', points: 10 },
    { id: 'cuddle', title: 'Momento de carinho', subtitle: 'Pele a pele ou massagem leve', points: 10 },
    { id: 'jr06', title: 'Conversa face a face', subtitle: 'Mimica e sons suaves', points: 12 },
    { id: 'jr07', title: 'Brincadeira com paninho colorido', subtitle: 'Rastrear com os olhos', points: 10 },
    { id: 'jr08', title: 'Móbile ou balão na linha de visão', subtitle: 'Foco e calma', points: 8 },
    { id: 'jr09', title: 'Música calma 5 minutos', subtitle: 'Rotina auditiva', points: 12 },
    { id: 'jr10', title: 'Espelho seguro no chão', subtitle: 'Descoberta do próprio rosto', points: 10 },
    { id: 'jr11', title: 'Alongar perninhas com leveza', subtitle: 'Movimento consciente', points: 10 },
    { id: 'jr12', title: 'Rolagem assistida (lado a lado)', subtitle: 'Sempre com apoio', points: 15 },
    { id: 'jr13', title: 'Brinquedo texturizado na mão', subtitle: 'Exploração tátil', points: 10 },
    { id: 'jr14', title: 'Hora do banho sem pressa', subtitle: 'Água morna e presença', points: 15 },
    { id: 'jr15', title: 'Soneca com ruído branco baixo', subtitle: 'Se fizer sentido para vocês', points: 8 },
    { id: 'jr16', title: 'Cante uma frase e pause', subtitle: 'Turno de “conversa”', points: 12 },
    { id: 'jr17', title: 'Brincar de esconder o rosto (devagar)', subtitle: 'Antecipação suave', points: 12 },
    { id: 'jr18', title: 'Passeio no colo pela casa', subtitle: 'Mudança de perspetiva', points: 10 },
    { id: 'jr19', title: 'Luz suave pela janela (sem sol direto)', subtitle: 'Estímulo visual', points: 8 },
    { id: 'jr20', title: 'Nomear objetos ao redor', subtitle: 'Vocabulário do dia a dia', points: 12 },
    { id: 'jr21', title: 'Massagem nos pezinhos', subtitle: 'Toque relaxante', points: 10 },
    { id: 'jr22', title: 'Brincar com chocalho suave', subtitle: 'Som e movimento', points: 10 },
    { id: 'jr23', title: 'Tempo no tapete macio', subtitle: 'Explorar posições com segurança', points: 12 },
    { id: 'jr24', title: 'Imitar um bocejo ou espirro (com humor)', subtitle: 'Imitação social', points: 10 },
    { id: 'jr25', title: 'Leitura de imagem (só olhar o livro)', subtitle: 'Sem precisar ler texto', points: 15 },
    { id: 'jr26', title: 'Descanso com música instrumental', subtitle: 'Regulação emocional', points: 8 },
    { id: 'jr27', title: 'Observar pássaros ou árvores', subtitle: 'Natureza em silêncio', points: 10 },
    { id: 'jr28', title: 'Brincadeira com bolas de cores', subtitle: 'Rolar e apanhar', points: 12 },
    { id: 'jr29', title: 'Higiene do rosto com pano morno', subtitle: 'Rotina de cuidado', points: 10 },
    { id: 'jr30', title: 'Descobrir cheiros seguros (baunilha, lavanda)', subtitle: 'Sensorial com moderação', points: 10 },
    { id: 'jr31', title: 'Subir e descer pernas em bicicleta', subtitle: 'Movimento ativo assistido', points: 12 },
    { id: 'jr32', title: 'Brincar com sombras na parede', subtitle: 'Luz e movimento', points: 10 },
    { id: 'jr33', title: 'Momento de gratidão em voz alta', subtitle: 'Vínculo e rotina positiva', points: 10 },
    { id: 'jr34', title: 'Arrastar macio no tapete', subtitle: 'Deslizar com supervisão', points: 15 },
    { id: 'jr35', title: 'Ouvir sons da cozinha', subtitle: 'Áudio familiar', points: 8 },
    { id: 'jr36', title: 'Brincar com água na bacia (supervisionado)', subtitle: 'Sensorial simples', points: 15 },
    { id: 'jr37', title: 'Contar dedinhos com calma', subtitle: 'Ritmo e contato', points: 10 },
    { id: 'jr38', title: 'Fotografia espontânea (sem flash)', subtitle: 'Registo leve do dia', points: 12 },
    { id: 'jr39', title: 'Respiração lenta junto', subtitle: 'Sincronizar o ritmo', points: 10 },
    { id: 'jr40', title: 'Brincar com cachecol leve', subtitle: 'Movimento e riso', points: 10 },
    { id: 'jr41', title: 'Explorar caixa sensorial segura', subtitle: 'Materiais grandes, sem risco', points: 15 },
    { id: 'jr42', title: 'Momento de silêncio abraçados', subtitle: 'Regulação e presença', points: 10 },
    { id: 'jr43', title: 'Nomear emoções num livro', subtitle: '“Está feliz, está surpreso…”', points: 12 },
    { id: 'jr44', title: 'Brincar com bolhas de sabão', subtitle: 'Perseguir e estourar', points: 12 },
    { id: 'jr45', title: 'Rastejar em superfície antiderrapante', subtitle: 'Motricidade com apoio', points: 18 },
    { id: 'jr46', title: 'Ouvir um instrumento simples', subtitle: 'Violão ou piano suave', points: 12 },
    { id: 'jr47', title: 'Arrumar um brinquedo junto', subtitle: 'Rotina e imitação', points: 10 },
    { id: 'jr48', title: 'Beber água em pausa lúdica', subtitle: 'Hidratação com ritual', points: 8 },
    { id: 'jr49', title: 'Desenhar com dedo na espuma', subtitle: 'Criatividade tátil', points: 12 },
    { id: 'jr50', title: 'Despedida do dia com frase fixa', subtitle: 'Previsibilidade à noite', points: 10 },
  ];

  g.MM_MYDAY_POOL = [
    { id: 'tummy', title: 'Hora da barriguinha', subtitle: '15 min fortalecendo pescoço e costas', points: 15, minutes: 15, moods: ['calmo', 'conectar'], maxAge: 18 },
    { id: 'story', title: 'Ler uma história curtinha', subtitle: 'Vocabulário e vínculo', points: 25, minutes: 15, moods: ['calmo', 'conectar', 'corrido'], maxAge: 72 },
    { id: 'song', title: 'Cantar ou ouvir uma música', subtitle: 'Estímulo auditivo e rotina', points: 10, minutes: 5, moods: ['calmo', 'sono', 'conectar'], maxAge: 120 },
    { id: 'mirror', title: 'Brincar frente ao espelho', subtitle: 'Contato visual e descoberta', points: 10, minutes: 5, moods: ['calmo', 'conectar'], maxAge: 24 },
    { id: 'massage', title: 'Massagem suave nas perninhas', subtitle: 'Relaxamento e toque', points: 10, minutes: 10, moods: ['calmo', 'sono'], maxAge: 36 },
    { id: 'outdoor', title: 'Ar puro por alguns minutos', subtitle: 'Sensorial e mudança de cenário', points: 15, minutes: 15, moods: ['calmo', 'corrido', 'conectar'], maxAge: 120 },
    { id: 'tummy_short', title: 'Barriguinha rápida (5 min)', subtitle: 'Versão curta para dia corrido', points: 10, minutes: 5, moods: ['corrido', 'calmo'], maxAge: 18 },
    { id: 'peekaboo', title: 'Bate-bate escondido', subtitle: 'Risos e antecipação', points: 10, minutes: 5, moods: ['calmo', 'conectar', 'corrido'], maxAge: 48 },
    { id: 'highchair', title: 'Conversa na hora da papinha', subtitle: 'Linguagem e rotina', points: 15, minutes: 15, moods: ['calmo', 'conectar'], minAge: 5, maxAge: 36 },
    { id: 'walk_hold', title: 'Apoio para ficar em pé (com supervisão)', subtitle: 'Exploração motora', points: 20, minutes: 10, moods: ['calmo', 'conectar'], minAge: 6, maxAge: 18 },
    { id: 'photo', title: 'Registrar um momento (foto ou frase)', subtitle: 'Memória na galeria', points: 20, minutes: 5, moods: ['calmo', 'corrido', 'sono', 'conectar'], maxAge: 120 },
    { id: 'cuddle', title: 'Só um colinho sem pressa', subtitle: 'Regulação e vínculo', points: 15, minutes: 10, moods: ['sono', 'conectar', 'calmo'], maxAge: 120 },
    { id: 'faces', title: 'Imitar caretas e sons', subtitle: 'Imitação e social', points: 10, minutes: 5, moods: ['conectar', 'calmo'], maxAge: 36 },
    { id: 'md14', title: 'Brincar com pano de cores', subtitle: 'Rastrear e apanhar', points: 10, minutes: 5, moods: ['calmo', 'conectar', 'corrido'], maxAge: 48 },
    { id: 'md15', title: 'Ouvir sons da natureza (app ou janela)', subtitle: 'Audição calmante', points: 8, minutes: 5, moods: ['calmo', 'sono'], maxAge: 120 },
    { id: 'md16', title: 'Rolar bola macia devagar', subtitle: 'Coordenação olho-mão', points: 12, minutes: 10, moods: ['calmo', 'conectar'], minAge: 4, maxAge: 48 },
    { id: 'md17', title: 'Empilhar 2–3 blocos grandes', subtitle: 'Motricidade fina', points: 12, minutes: 10, moods: ['calmo', 'conectar', 'corrido'], minAge: 8, maxAge: 36 },
    { id: 'md18', title: 'Pintar com dedo (papel + cor segura)', subtitle: 'Arte sem pressa', points: 15, minutes: 15, moods: ['calmo', 'conectar'], minAge: 10, maxAge: 60 },
    { id: 'md19', title: 'Caça ao tesouro no quarto', subtitle: 'Objetos grandes e seguros', points: 15, minutes: 15, moods: ['conectar', 'corrido'], minAge: 12, maxAge: 72 },
    { id: 'md20', title: 'Dança lenta 2 músicas', subtitle: 'Ritmo e proximidade', points: 12, minutes: 10, moods: ['calmo', 'conectar', 'sono'], maxAge: 120 },
    { id: 'md21', title: 'Soprar bolhas juntos', subtitle: 'Sopro e perseguição', points: 10, minutes: 10, moods: ['calmo', 'conectar'], minAge: 18, maxAge: 72 },
    { id: 'md22', title: 'Leitura só com imagens', subtitle: 'Nomear o que vê', points: 12, minutes: 10, moods: ['calmo', 'corrido', 'conectar'], maxAge: 120 },
    { id: 'md23', title: 'Brincar com água na bacia', subtitle: 'Supervisão constante', points: 15, minutes: 15, moods: ['calmo', 'conectar'], minAge: 6, maxAge: 48 },
    { id: 'md24', title: 'Subir escadas com apoio (se houver)', subtitle: 'Só com adulto colado', points: 18, minutes: 10, moods: ['calmo', 'conectar'], minAge: 12, maxAge: 36 },
    { id: 'md25', title: 'Jogo de encaixar formas grandes', subtitle: 'Resolução de problemas', points: 15, minutes: 15, moods: ['calmo', 'conectar'], minAge: 10, maxAge: 48 },
    { id: 'md26', title: 'Imitar animais (som + gesto)', subtitle: 'Linguagem corporal', points: 12, minutes: 10, moods: ['conectar', 'calmo'], maxAge: 60 },
    { id: 'md27', title: 'Caminhada lenta no corredor', subtitle: 'Exploração segura', points: 10, minutes: 10, moods: ['corrido', 'calmo', 'conectar'], minAge: 9, maxAge: 72 },
    { id: 'md28', title: 'Brincar com luz e sombra', subtitle: 'Estímulo visual simples', points: 10, minutes: 5, moods: ['calmo', 'conectar'], maxAge: 36 },
    { id: 'md29', title: 'Contar dedos e beijinhos', subtitle: 'Afeto e número', points: 8, minutes: 5, moods: ['sono', 'calmo', 'conectar'], maxAge: 120 },
    { id: 'md30', title: 'Montar circuito macio no chão', subtitle: 'Rastejar ou rolar', points: 15, minutes: 15, moods: ['calmo', 'conectar'], maxAge: 18 },
    { id: 'md31', title: 'Brincar de telefone com caixa', subtitle: 'Conversas imaginárias', points: 10, minutes: 10, moods: ['conectar', 'corrido'], minAge: 12, maxAge: 60 },
    { id: 'md32', title: 'Plantar semente num vasinho', subtitle: 'Natureza e rotina', points: 15, minutes: 20, moods: ['calmo', 'conectar'], minAge: 24, maxAge: 120 },
    { id: 'md33', title: 'Separar cores com objetos grandes', subtitle: 'Atencão compartilhada', points: 12, minutes: 15, moods: ['calmo', 'conectar'], minAge: 18, maxAge: 48 },
    { id: 'md34', title: 'Momento de gratidão em voz alta', subtitle: 'Uma frase sobre o dia', points: 10, minutes: 5, moods: ['calmo', 'conectar'], maxAge: 120 },
    { id: 'md35', title: 'Brincar com fita crepe na mesa', subtitle: 'Descolar e colar', points: 10, minutes: 10, moods: ['corrido', 'calmo'], minAge: 12, maxAge: 48 },
    { id: 'md36', title: 'Esconder brinquedo sob pano', subtitle: 'Objeto permanente', points: 12, minutes: 10, moods: ['calmo', 'conectar'], maxAge: 36 },
    { id: 'md37', title: 'Cantar contagem regressiva de 3', subtitle: 'Antecipação brincalhona', points: 10, minutes: 5, moods: ['conectar', 'corrido'], maxAge: 60 },
    { id: 'md38', title: 'Massagem com óleo morno (se indicado)', subtitle: 'Rotina relaxante', points: 12, minutes: 15, moods: ['sono', 'calmo'], maxAge: 36 },
    { id: 'md39', title: 'Brincar com ímãs grandes na geladeira', subtitle: 'Causa e efeito', points: 10, minutes: 10, moods: ['calmo', 'conectar'], minAge: 18, maxAge: 60 },
    { id: 'md40', title: 'Passeio pelo quintal ou varanda', subtitle: 'Ar e texturas', points: 12, minutes: 15, moods: ['calmo', 'corrido', 'conectar'], maxAge: 120 },
    { id: 'md41', title: 'Empurrar carrinho ou caixa leve', subtitle: 'Marcha assistida', points: 15, minutes: 15, moods: ['conectar', 'corrido'], minAge: 10, maxAge: 36 },
    { id: 'md42', title: 'Brincar com massinha comestível', subtitle: 'Exploração segura', points: 15, minutes: 20, moods: ['calmo', 'conectar'], minAge: 8, maxAge: 48 },
    { id: 'md43', title: 'Ver um vídeo curto educativo', subtitle: 'Máx. 5–10 min, junto', points: 10, minutes: 10, moods: ['corrido', 'sono', 'calmo'], maxAge: 120 },
    { id: 'md44', title: 'Arrumar brinquedos em caixa', subtitle: 'Rotina e limites', points: 12, minutes: 10, moods: ['corrido', 'calmo'], minAge: 18, maxAge: 72 },
    { id: 'md45', title: 'Brincar de “acorda boneco”', subtitle: 'Cuidado e imitação', points: 10, minutes: 10, moods: ['conectar', 'calmo'], maxAge: 48 },
    { id: 'md46', title: 'Soprar penas ou folhas', subtitle: 'Sopro e perseguição', points: 10, minutes: 10, moods: ['calmo', 'conectar'], minAge: 24, maxAge: 72 },
    { id: 'md47', title: 'Desenhar na areia ou na mesa', subtitle: 'Traços livres', points: 12, minutes: 15, moods: ['calmo', 'conectar'], minAge: 18, maxAge: 120 },
    { id: 'md48', title: 'Brincar com corda ou pano puxando', subtitle: 'Força e riso', points: 12, minutes: 10, moods: ['conectar', 'corrido'], minAge: 8, maxAge: 48 },
    { id: 'md49', title: 'Momento de silêncio 1 minuto', subtitle: 'Respirar junto', points: 8, minutes: 5, moods: ['sono', 'calmo'], maxAge: 120 },
    { id: 'md50', title: 'Planejar o dia seguinte em uma frase', subtitle: 'Previsibilidade positiva', points: 10, minutes: 5, moods: ['calmo', 'conectar'], maxAge: 120 },
  ];
})(typeof window !== 'undefined' ? window : this);
